<?php
/**
 * Installer Class - Main Installation Logic
 */

class Installer {

    private $baseDir;
    private $pdo;
    private $config = [];
    private array $triggerWarnings = [];

    public function __construct($baseDir) {
        $this->baseDir = rtrim($baseDir, '/');
    }

    /**
     * Create .env file with database configuration
     */
    public function createEnvFile($host, $user, $password, $database, $port = 3306, $socket = '', $locale = 'it') {
        $envPath = $this->baseDir . '/.env';

        $envContent = "# Environment Configuration - Sistema Biblioteca\n";
        $envContent .= "# Generated by installer on " . date('Y-m-d H:i:s') . "\n";
        $envContent .= "# IMPORTANT: Keep this file secure and never commit it to version control\n\n";

        $envContent .= "# Database Configuration\n";
        $envContent .= "DB_HOST={$host}\n";
        $envContent .= "DB_USER={$user}\n";
        $envContent .= "DB_PASS={$password}\n";
        $envContent .= "DB_NAME={$database}\n";
        $envContent .= "DB_PORT={$port}\n";
        $envContent .= "DB_SOCKET={$socket}\n\n";

        $envContent .= "# Application Environment\n";
        $envContent .= "# Set to 'production' for live environments, 'development' for local dev\n";
        $envContent .= "APP_ENV=production\n\n";

        $envContent .= "# Application Language\n";
        $envContent .= "# Default language for the entire application (it = Italian, en = English)\n";
        $envContent .= "APP_LOCALE={$locale}\n\n";

        $envContent .= "# Debug Mode\n";
        $envContent .= "# MUST be false in production for security reasons\n";
        $envContent .= "APP_DEBUG=false\n\n";

        $envContent .= "# Session Security\n";
        $envContent .= "# Session lifetime in seconds (default: 3600 = 1 hour)\n";
        $envContent .= "SESSION_LIFETIME=3600\n\n";

        $envContent .= "# Display Errors\n";
        $envContent .= "# MUST be false in production (errors logged instead of displayed)\n";
        $envContent .= "DISPLAY_ERRORS=false\n\n";

        $envContent .= "# Force HTTPS\n";
        $envContent .= "# Set to 'true' only if your server supports HTTPS (requires valid SSL certificate)\n";
        $envContent .= "# Leave 'false' for local development or HTTP-only production servers\n";
        $envContent .= "FORCE_HTTPS=false\n";
        $envContent .= "\n# Canonical URL (auto-detected during installation)\n";
        $envContent .= "APP_CANONICAL_URL=" . $this->detectCanonicalUrl() . "\n";

        return file_put_contents($envPath, $envContent) !== false;
    }

    /**
     * Load database configuration from .env
     */
    public function loadEnvConfig() {
        $envPath = $this->baseDir . '/.env';

        if (!file_exists($envPath)) {
            throw new Exception("File .env non trovato");
        }

        $lines = file($envPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);

        foreach ($lines as $line) {
            if (strpos($line, '=') !== false && !str_starts_with(trim($line), '#')) {
                [$key, $value] = explode('=', $line, 2);
                $this->config[trim($key)] = trim($value, '"\'');
            }
        }

        return true;
    }

    /**
     * Get database connection
     */
    public function getDatabaseConnection() {
        if ($this->pdo) {
            return $this->pdo;
        }

        $host = $this->config['DB_HOST'] ?? 'localhost';
        $port = (int)($this->config['DB_PORT'] ?? 3306);
        $database = $this->config['DB_NAME'] ?? '';
        $username = $this->config['DB_USER'] ?? 'root';
        $password = $this->config['DB_PASS'] ?? '';
        $socket = $this->config['DB_SOCKET'] ?? '';

        // Build DSN
        $dsn = "mysql:";

        if (!empty($socket)) {
            $dsn .= "unix_socket={$socket};";
        } elseif ($host === 'localhost') {
            $socketPaths = [
                '/tmp/mysql.sock',
                '/var/run/mysqld/mysqld.sock',
                '/usr/local/var/mysql/mysql.sock',
                '/opt/homebrew/var/mysql/mysql.sock'
            ];

            $found = false;
            foreach ($socketPaths as $path) {
                if (file_exists($path)) {
                    $dsn .= "unix_socket={$path};";
                    $found = true;
                    break;
                }
            }

            if (!$found) {
                $dsn .= "host={$host};port={$port};";
            }
        } else {
            $dsn .= "host={$host};port={$port};";
        }

        $dsn .= "dbname={$database};charset=utf8mb4";

        $this->pdo = new PDO($dsn, $username, $password, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
        ]);

        return $this->pdo;
    }

    /**
     * Import database schema using MySQL CLI or PDO fallback
     */
    public function importSchema() {
        // Use absolute path to avoid issues with chdir()
        $installerDir = dirname(__DIR__);
        $schemaFile = $installerDir . '/database/schema.sql';

        if (!file_exists($schemaFile)) {
            // Try to resolve the real path
            $realSchemaFile = realpath($installerDir . '/database/schema.sql');
            if ($realSchemaFile === false) {
                throw new Exception("File schema.sql non trovato. Cercato in: " . $schemaFile . " (installer dir: " . $installerDir . ")");
            }
            $schemaFile = $realSchemaFile;
        }

        // Try exec() method first (faster and more reliable)
        if (function_exists('exec')) {
            try {
                return $this->importSchemaViaExec($schemaFile);
            } catch (Exception $e) {
                // If exec() fails, fall back to PDO method
                error_log("exec() method failed, falling back to PDO: " . $e->getMessage());
            }
        }

        // Fallback to PDO method (works on all hosting, including those with exec() disabled)
        return $this->importSchemaViaPDO($schemaFile);
    }

    /**
     * Import initial data (classificazione, generi, email_templates)
     */
    public function importData() {
        $installerDir = dirname(__DIR__);

        // Determine locale from APP_LOCALE config (set in .env during installation)
        // Default to it_IT if not set
        $locale = $this->config['APP_LOCALE'] ?? 'it';

        // Convert short locale (it, en) to full locale (it_IT, en_US)
        $localeMap = [
            'it' => 'it_IT',
            'en' => 'en_US',
        ];
        $fullLocale = $localeMap[$locale] ?? 'it_IT';

        // Try locale-specific data file first (data_it_IT.sql or data_en_US.sql)
        $dataFile = $installerDir . '/database/data_' . $fullLocale . '.sql';

        // Fallback to generic data.sql if locale-specific file doesn't exist
        if (!file_exists($dataFile)) {
            $dataFile = $installerDir . '/database/data.sql';
        }

        // Data file is optional - if missing, skip
        if (!file_exists($dataFile)) {
            return true;
        }

        // Try exec() method first (faster and more reliable)
        if (function_exists('exec')) {
            try {
                return $this->importDataViaExec($dataFile);
            } catch (Exception $e) {
                error_log("exec() method failed for data import, falling back to PDO: " . $e->getMessage());
            }
        }

        // Fallback to PDO method
        return $this->importDataViaPDO($dataFile);
    }

    /**
     * Import schema using MySQL CLI (faster but requires exec())
     */
    private function importSchemaViaExec($schemaFile) {
        $host = $this->config['DB_HOST'] ?? 'localhost';
        $port = (int)($this->config['DB_PORT'] ?? 3306);
        $database = $this->config['DB_NAME'] ?? '';
        $username = $this->config['DB_USER'] ?? 'root';
        $password = $this->config['DB_PASS'] ?? '';

        // Build mysql command
        $cmd = 'mysql';
        $cmd .= ' -h ' . escapeshellarg($host);
        $cmd .= ' -P ' . (int)$port;
        $cmd .= ' -u ' . escapeshellarg($username);
        if (!empty($password)) {
            $cmd .= ' -p' . escapeshellarg($password);
        }
        $cmd .= ' --default-character-set=utf8mb4'; // Force UTF-8 to prevent encoding corruption (📚 → ðŸ"š, È → Ãˆ)
        $cmd .= ' ' . escapeshellarg($database);
        $cmd .= ' < ' . escapeshellarg($schemaFile);

        // Execute mysql command
        $output = [];
        $exitCode = 0;
        exec($cmd . ' 2>&1', $output, $exitCode);

        if ($exitCode !== 0) {
            $errorMsg = implode("\n", $output);
            throw new Exception("Errore importazione schema (exit code: $exitCode): " . $errorMsg);
        }

        return $this->verifySchemaImport();
    }

    /**
     * Import schema using PDO (works on all hosting)
     */
    private function importSchemaViaPDO($schemaFile) {
        // Read schema file
        $sql = file_get_contents($schemaFile);
        if ($sql === false) {
            throw new Exception("Impossibile leggere il file schema.sql");
        }

        // Get PDO connection
        $pdo = $this->getDatabaseConnection();

        // Split SQL into statements
        // Remove comments and handle MySQL conditional comments
        $sql = preg_replace('/--.*$/m', '', $sql); // Remove single-line comments
        $sql = preg_replace('/\/\*(?!\!).*?\*\//s', '', $sql); // Remove normal multi-line comments (not /*!... */)
        // Unwrap MySQL conditional comments: /*!40101 SET ... */ becomes just: SET ...
        $sql = preg_replace('/\/\*!\d+\s*(.*?)\s*\*\//s', '$1', $sql);

        // Split by semicolon, but handle DELIMITER statements
        $statements = [];
        $buffer = '';
        $inDelimiter = false;

        foreach (explode("\n", $sql) as $line) {
            $trimmed = trim($line);

            // Check for DELIMITER command
            if (preg_match('/^DELIMITER\s+(.+)$/i', $trimmed, $matches)) {
                $inDelimiter = true;
                continue;
            }

            $buffer .= $line . "\n";

            // Check if statement ends
            if ($inDelimiter) {
                // Looking for $$ delimiter
                if (strpos($trimmed, '$$') !== false) {
                    $statements[] = trim($buffer);
                    $buffer = '';
                    $inDelimiter = false;
                }
            } else {
                // Standard semicolon delimiter
                if (substr($trimmed, -1) === ';') {
                    $statements[] = trim($buffer);
                    $buffer = '';
                }
            }
        }

        // Add remaining buffer if any
        if (!empty(trim($buffer))) {
            $statements[] = trim($buffer);
        }

        // Execute each statement
        $executedCount = 0;
        $errors = [];

        foreach ($statements as $statement) {
            $statement = trim($statement);

            // Skip empty statements
            if (empty($statement)) {
                continue;
            }

            // Skip DELIMITER statements
            if (preg_match('/^DELIMITER/i', $statement)) {
                continue;
            }

            try {
                $pdo->exec($statement);
                $executedCount++;
            } catch (PDOException $e) {
                // Some statements might fail (like IF NOT EXISTS checks)
                // Only collect real errors
                if (strpos($e->getMessage(), 'already exists') === false) {
                    $errors[] = "Statement error: " . $e->getMessage();
                }
            }
        }

        if (!empty($errors)) {
            error_log("Schema import warnings: " . implode("\n", $errors));
            // If too many errors, throw exception with first few errors for debugging
            if (count($errors) > 10) {
                $firstErrors = array_slice($errors, 0, 5);
                throw new Exception("Troppi errori durante l'import dello schema (" . count($errors) . " errori). Primi errori:\n" . implode("\n", $firstErrors));
            }
        }

        return $this->verifySchemaImport();
    }

    /**
     * Import data using MySQL CLI (faster but requires exec())
     */
    private function importDataViaExec($dataFile) {
        $host = $this->config['DB_HOST'] ?? 'localhost';
        $port = (int)($this->config['DB_PORT'] ?? 3306);
        $database = $this->config['DB_NAME'] ?? '';
        $username = $this->config['DB_USER'] ?? 'root';
        $password = $this->config['DB_PASS'] ?? '';

        // Build mysql command
        $cmd = 'mysql';
        $cmd .= ' -h ' . escapeshellarg($host);
        $cmd .= ' -P ' . (int)$port;
        $cmd .= ' -u ' . escapeshellarg($username);
        if (!empty($password)) {
            $cmd .= ' -p' . escapeshellarg($password);
        }
        $cmd .= ' --default-character-set=utf8mb4'; // Force UTF-8 to prevent encoding corruption (📚 → ðŸ"š, È → Ãˆ)
        $cmd .= ' ' . escapeshellarg($database);
        $cmd .= ' < ' . escapeshellarg($dataFile);

        // Execute mysql command
        $output = [];
        $exitCode = 0;
        exec($cmd . ' 2>&1', $output, $exitCode);

        if ($exitCode !== 0) {
            $errorMsg = implode("\n", $output);
            throw new Exception("Errore importazione dati (exit code: $exitCode): " . $errorMsg);
        }

        return true;
    }

    /**
     * Import data using PDO (works on all hosting)
     */
    private function importDataViaPDO($dataFile) {
        // Read data file
        $sql = file_get_contents($dataFile);
        if ($sql === false) {
            throw new Exception("Impossibile leggere il file data.sql");
        }

        // Get PDO connection
        $pdo = $this->getDatabaseConnection();

        // Split SQL into statements (simpler than schema - just INSERT statements)
        $statements = array_filter(explode(";\n", $sql), function($stmt) {
            return !empty(trim($stmt));
        });

        $executedCount = 0;
        $errors = [];

        foreach ($statements as $statement) {
            $statement = trim($statement);

            if (empty($statement)) {
                continue;
            }

            try {
                $pdo->exec($statement);
                $executedCount++;
            } catch (PDOException $e) {
                // Collect errors but continue (some INSERTs might fail due to duplicates)
                if (strpos($e->getMessage(), 'Duplicate entry') === false) {
                    $errors[] = "Data import error: " . $e->getMessage();
                }
            }
        }

        if (!empty($errors) && count($errors) > 10) {
            $firstErrors = array_slice($errors, 0, 5);
            throw new Exception("Troppi errori durante l'import dei dati (" . count($errors) . " errori). Primi errori:\n" . implode("\n", $firstErrors));
        }

        return true;
    }

    /**
     * Verify schema was imported correctly
     */
    private function verifySchemaImport() {
        // IMPORTANT: Close old PDO connection and reset it
        // This ensures new connections see the newly created tables
        $this->pdo = null;

        // Verify that tables were created with fresh connection
        try {
            $pdo = $this->getDatabaseConnection();
            $stmt = $pdo->query("SHOW TABLES");
            $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);

            if (count($tables) < 5) {
                throw new Exception("Schema non importato correttamente. Solo " . count($tables) . " tabelle trovate.");
            }
        } catch (PDOException $e) {
            throw new Exception("Errore verifica tabelle: " . $e->getMessage());
        }

        return true;
    }

    /**
     * Import database triggers
     */
    public function importTriggers() {
        $this->triggerWarnings = [];
        // Use absolute path to avoid issues with chdir()
        $installerDir = dirname(__DIR__);
        $triggersFile = $installerDir . '/database/triggers.sql';

        if (!file_exists($triggersFile)) {
            $this->triggerWarnings[] = "File triggers.sql non trovato — nessun trigger installato.";
            return true;
        }

        $sql = file_get_contents($triggersFile);

        if (!is_string($sql) || trim($sql) === '') {
            $this->triggerWarnings[] = "File triggers.sql vuoto — nessun trigger installato.";
            return true;
        }

        $pdo = $this->getDatabaseConnection();

        // Clean up DEFINER clauses and remove DELIMITER statements
        $sql = preg_replace('/CREATE\s+DEFINER=`[^`]+`@`[^`]+`\s+TRIGGER/i', 'CREATE TRIGGER', $sql);
        $sql = preg_replace('/DELIMITER\s+\S+/i', '', $sql);

        // Split the file into statements using '$$' as the delimiter
        $statements = explode('$$', $sql);

        $executedTriggers = 0;
        foreach ($statements as $statement) {
            $statement = trim($statement);
            if (empty($statement)) {
                continue;
            }

            try {
                $pdo->exec($statement);
                if (stripos($statement, 'CREATE TRIGGER') === 0) {
                    $executedTriggers++;
                }
            } catch (PDOException $e) {
                $message = $e->getMessage();
                $this->triggerWarnings[] = "Impossibile eseguire uno statement del trigger: {$message}";
                // Continue to the next statement
            }
        }

        if ($executedTriggers === 0 && empty($this->triggerWarnings)) {
            $this->triggerWarnings[] = "Nessun trigger valido trovato nel file triggers.sql.";
        }

        return true;
    }

    /**
     * Retrieve warnings generated during trigger import
     *
     * @return string[]
     */
    public function getTriggerWarnings(): array
    {
        return $this->triggerWarnings;
    }

    /**
     * Verify database installation
     */
    public function verifyInstallation() {
        $pdo = $this->getDatabaseConnection();

        // Count tables
        $stmt = $pdo->query("SHOW TABLES");
        $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);

        if (count($tables) !== 36) {
            throw new Exception("Installazione database non completa. Trovate " . count($tables) . " tabelle, attese 36");
        }

        // Check essential data
        $stmt = $pdo->query("SELECT COUNT(*) as count FROM classificazione");
        $result = $stmt->fetch();
        if ($result['count'] == 0) {
            throw new Exception("Dati di classificazione mancanti");
        }

        $stmt = $pdo->query("SELECT COUNT(*) as count FROM generi");
        $result = $stmt->fetch();
        if ($result['count'] == 0) {
            throw new Exception("Dati generi mancanti");
        }


        return true;
    }

    /**
     * Create admin user
     */
    public function createAdminUser($nome, $cognome, $email, $password) {

        $pdo = $this->getDatabaseConnection();

        // Decode HTML entities that might have been added during sanitization
        $nome = html_entity_decode($nome, ENT_QUOTES, 'UTF-8');
        $cognome = html_entity_decode($cognome, ENT_QUOTES, 'UTF-8');

        // Generate unique codice_tessera
        $codiceTessera = 'ADMIN-' . date('Ymd') . '-' . str_pad((string)rand(1, 999), 3, '0', STR_PAD_LEFT);

        // Hash password
        $passwordHash = password_hash($password, PASSWORD_BCRYPT);

        // Insert admin user
        $query = "
            INSERT INTO utenti (
                nome, cognome, email, password, codice_tessera,
                tipo_utente, stato, email_verificata,
                data_scadenza_tessera, created_at, updated_at
            ) VALUES (
                :nome, :cognome, :email, :password, :codice_tessera,
                'admin', 'attivo', 1,
                DATE_ADD(NOW(), INTERVAL 10 YEAR), NOW(), NOW()
            )
        ";

        try {
            $stmt = $pdo->prepare($query);

            $stmt->execute([
                'nome' => $nome,
                'cognome' => $cognome,
                'email' => $email,
                'password' => $passwordHash,
                'codice_tessera' => $codiceTessera
            ]);

            $userId = $pdo->lastInsertId();

            return [
                'id' => $userId,
                'codice_tessera' => $codiceTessera
            ];
        } catch (PDOException $e) {
            throw $e;
        }
    }

    /**
     * Save application settings
     */
    public function saveSetting($category, $key, $value) {
        $pdo = $this->getDatabaseConnection();

        // Check if setting exists
        $stmt = $pdo->prepare("SELECT id FROM system_settings WHERE category = :category AND setting_key = :key");
        $stmt->execute(['category' => $category, 'key' => $key]);
        $exists = $stmt->fetch();

        if ($exists) {
            // Update
            $stmt = $pdo->prepare("
                UPDATE system_settings
                SET setting_value = :value, updated_at = NOW()
                WHERE category = :category AND setting_key = :key
            ");
        } else {
            // Insert
            $stmt = $pdo->prepare("
                INSERT INTO system_settings (category, setting_key, setting_value, created_at, updated_at)
                VALUES (:category, :key, :value, NOW(), NOW())
            ");
        }

        $stmt->execute([
            'category' => $category,
            'key' => $key,
            'value' => $value
        ]);

        return true;
    }

    /**
     * Upload and save logo
     */
    public function uploadLogo($file) {
        $uploadDir = $this->baseDir . '/uploads/assets';

        if (!is_dir($uploadDir)) {
            mkdir($uploadDir, 0755, true);
        }

        // Generate unique filename
        $extension = pathinfo($file['name'], PATHINFO_EXTENSION);
        $filename = 'logo_' . uniqid() . '.' . $extension;
        $destination = $uploadDir . '/' . $filename;

        if (!move_uploaded_file($file['tmp_name'], $destination)) {
            throw new Exception("Impossibile salvare il logo");
        }

        return '/uploads/assets/' . $filename;
    }

    /**
     * Create default .htaccess if missing
     */
    public function createHtaccess() {
        $htaccessPath = $this->baseDir . '/.htaccess';

        if (file_exists($htaccessPath)) {
            return true; // Already exists
        }

        $htaccessContent = <<<'HTACCESS'
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /

    # Redirect all requests to index.php
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>

# Disable directory browsing
Options -Indexes

# Protect sensitive files
<FilesMatch "^\.">
    Order allow,deny
    Deny from all
</FilesMatch>

<FilesMatch "^(composer\.(json|lock)|package(-lock)?\.json|\.env.*|.*\.md)$">
    Order allow,deny
    Deny from all
</FilesMatch>
HTACCESS;

        return file_put_contents($htaccessPath, $htaccessContent) !== false;
    }

    /**
     * Create installation lock file
     */
    public function createLockFile() {
        $lockFile = dirname(dirname(__DIR__)) . '/.installed';
        $lockContent = "Installed on: " . date('Y-m-d H:i:s') . "\n";
        $lockContent .= "Do not delete this file. It prevents re-installation.\n";

        return file_put_contents($lockFile, $lockContent) !== false;
    }

    /**
     * Check if installer is locked (already installed)
     */
    public function isInstalled() {
        return file_exists(dirname(dirname(__DIR__)) . '/.installed');
    }

    /**
     * Populate default system settings
     */
    public function populateDefaultSettings() {
        $defaults = [
            // Registration
            ['registration', 'require_admin_approval', '1'],

            // Contacts (empty defaults)
            ['contacts', 'page_title', 'Contattaci'],
            ['contacts', 'page_content', '<p>Contattaci per qualsiasi informazione.</p>'],
            ['contacts', 'contact_email', ''],
            ['contacts', 'contact_phone', ''],
            ['contacts', 'notification_email', ''],
            ['contacts', 'privacy_text', 'I tuoi dati sono protetti secondo la nostra privacy policy.'],

            // Privacy
            ['privacy', 'page_title', 'Privacy Policy'],
            ['privacy', 'page_content', '<p>Privacy policy...</p>'],
            ['privacy', 'cookie_banner_enabled', '0'],
            ['privacy', 'cookie_banner_language', 'it']
        ];

        foreach ($defaults as [$category, $key, $value]) {
            try {
                $this->saveSetting($category, $key, $value);
            } catch (Exception $e) {
                // Ignore if already exists
            }
        }

        return true;
    }

    /**
     * Detect canonical URL of the current installation request.
     */
    private function detectCanonicalUrl(): string
    {
        $scheme = 'http';

        if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
            $forwardedProto = explode(',', (string)$_SERVER['HTTP_X_FORWARDED_PROTO'])[0];
            $scheme = strtolower($forwardedProto) === 'https' ? 'https' : 'http';
        } elseif (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') {
            $scheme = 'https';
        } elseif (!empty($_SERVER['REQUEST_SCHEME'])) {
            $scheme = strtolower((string)$_SERVER['REQUEST_SCHEME']) === 'https' ? 'https' : 'http';
        } elseif (isset($_SERVER['SERVER_PORT']) && (int)$_SERVER['SERVER_PORT'] === 443) {
            $scheme = 'https';
        }

        $host = 'localhost';
        if (!empty($_SERVER['HTTP_X_FORWARDED_HOST'])) {
            $host = explode(',', (string)$_SERVER['HTTP_X_FORWARDED_HOST'])[0];
        } elseif (!empty($_SERVER['HTTP_HOST'])) {
            $host = (string)$_SERVER['HTTP_HOST'];
        } elseif (!empty($_SERVER['SERVER_NAME'])) {
            $host = (string)$_SERVER['SERVER_NAME'];
        }

        $port = null;
        if (str_contains($host, ':')) {
            [$hostOnly, $portPart] = explode(':', $host, 2);
            $host = $hostOnly;
            $port = is_numeric($portPart) ? (int)$portPart : null;
        } elseif (!empty($_SERVER['HTTP_X_FORWARDED_PORT'])) {
            $port = (int)$_SERVER['HTTP_X_FORWARDED_PORT'];
        } elseif (isset($_SERVER['SERVER_PORT']) && is_numeric((string)$_SERVER['SERVER_PORT'])) {
            $port = (int)$_SERVER['SERVER_PORT'];
        }

        $base = $scheme . '://' . $host;
        $defaultPorts = ['http' => 80, 'https' => 443];
        if ($port !== null && ($defaultPorts[$scheme] ?? null) !== $port) {
            $base .= ':' . $port;
        }

        return rtrim($base, '/');
    }

    /**
     * Delete installer directory for security
     */
    public function deleteInstaller() {
        $installerDir = dirname(__DIR__);
        return $this->recursiveDelete($installerDir);
    }

    /**
     * Recursively delete directory
     */
    private function recursiveDelete($dir) {
        if (!is_dir($dir)) {
            return false;
        }

        $files = array_diff(scandir($dir), ['.', '..']);

        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            is_dir($path) ? $this->recursiveDelete($path) : unlink($path);
        }

        return rmdir($dir);
    }
}
