-- Initial data for Pinakes
-- Generated by installer

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('cookie_banner', 'enabled', '1', 'Enable cookie consent banner'),
('cookie_banner', 'position', 'bottom', 'Position of the cookie banner'),
('cookie_banner', 'layout', 'bar', 'Layout of the cookie banner'),
('cookie_banner', 'theme', 'light', 'Color theme for the cookie banner'),
('cookie_banner', 'primary_color', '#2563eb', 'Primary color for buttons and highlights'),
('cookie_banner', 'text_color', '#111827', 'Color of the main text in the banner'),
('cookie_banner', 'background_color', '#ffffff', 'Background color of the banner'),
('cookie_banner', 'backdrop', '1', 'Show a subtle page backdrop behind the banner'),
('cookie_banner', 'message', 'We use technical and analytical cookies to ensure the correct functioning of the site and improve your browsing experience. You can accept all cookies or customize your preferences.', 'Main message shown in the cookie banner'),
('cookie_banner', 'accept_text', 'Accept all', 'Label for the full acceptance button'),
('cookie_banner', 'reject_text', 'Reject non-essential', 'Label for the button that rejects non-essential cookies'),
('cookie_banner', 'settings_text', 'Customize', 'Label for the button that opens the cookie preferences panel'),
('cookie_banner', 'details_title', 'Cookie Preferences', 'Title of the preferences modal/panel'),
('cookie_banner', 'details_description', 'Select the categories of cookies you want to enable. You can change your preferences at any time from the site footer.', 'Description shown in the preferences panel'),
('cookie_banner', 'necessary_title', 'Strictly necessary cookies', 'Title for strictly necessary cookies section'),
('cookie_banner', 'necessary_description', 'These cookies are essential for the correct functioning of the site and cannot be disabled.', 'Description for strictly necessary cookies'),
('cookie_banner', 'analytics_title', 'Analytics cookies', 'Title for analytics cookies section'),
('cookie_banner', 'analytics_description', 'These cookies help us understand how the site is used, in order to improve navigation and the quality of our services.', 'Description for analytics cookies'),
('cookie_banner', 'thirdparty_title', 'Third-party cookies', 'Title for third-party cookies section'),
('cookie_banner', 'thirdparty_description', 'These cookies may be set by external services integrated into the site (for example, videos, maps, social widgets).', 'Description for third-party cookies'),
('cookie_banner', 'save_preferences_text', 'Save preferences', 'Label for the button that saves cookie preferences'),
('cookie_banner', 'learn_more_text', 'Learn more', 'Label for the link/button that opens more information (e.g. Privacy Policy)'),
('cookie_banner', 'policy_link', '/privacy-policy', 'URL of the Privacy Policy page linked from the banner');
INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('privacy', 'cookie_policy_content', '<p>This page explains how we use cookies on our website.</p>', 'Content displayed on /cookies');
INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('cms', 'events_page_enabled', '1', 'Enable or disable the events page on the frontend');
INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('system', 'catalogue_mode', '0', 'Catalogue-only mode - disables loans, reservations and wishlist');


SET FOREIGN_KEY_CHECKS=1;
