-- Initial data for Pinakes
-- Generated by installer

SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('cms', 'events_page_enabled', '1', 'Aktiver eller deaktiver begivenhedssiden på frontend')
ON DUPLICATE KEY UPDATE description = VALUES(description), updated_at = NOW();

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('system', 'catalogue_mode', '0', 'Kun katalog-tilstand – deaktiverer lån, reservationer og ønskeliste')
ON DUPLICATE KEY UPDATE description = VALUES(description), updated_at = NOW();

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('loans', 'pickup_expiry_days', '3', 'Antal dage til at afhente et godkendt lån, før det udløber')
ON DUPLICATE KEY UPDATE description = VALUES(description), updated_at = NOW();

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('loans', 'loan_duration_days', '30', 'Standardvarighed for et lån i dage')
ON DUPLICATE KEY UPDATE description = VALUES(description), updated_at = NOW();

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('loans', 'max_active_loans_per_user', '0', 'Maksimalt antal aktive lån pr. bruger (0 = ingen grænse)')
ON DUPLICATE KEY UPDATE description = VALUES(description), updated_at = NOW();

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('loans', 'max_renewals', '3', 'Maksimalt antal fornyelser tilladt pr. lån')
ON DUPLICATE KEY UPDATE description = VALUES(description), updated_at = NOW();

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`) VALUES
('loans', 'max_loan_duration_days', '90', 'Maksimal lånevarighed, der kan anmodes om, i dage')
ON DUPLICATE KEY UPDATE description = VALUES(description), updated_at = NOW();

INSERT INTO `generi` VALUES (1,'Prosa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT INTO `generi` VALUES (2,'Poesi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT INTO `generi` VALUES (3,'Teater',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',NULL);
INSERT INTO `generi` VALUES (4,'Skønlitteratur',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT INTO `generi` VALUES (5,'Faglitteratur',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT INTO `generi` VALUES (6,'Veltalenhed',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',1);
INSERT INTO `generi` VALUES (7,'Epik',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT INTO `generi` VALUES (8,'Didaktisk digtning',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT INTO `generi` VALUES (9,'Lyrik',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',2);
INSERT INTO `generi` VALUES (10,'Prosateater',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',3);
INSERT INTO `generi` VALUES (11,'Musikteater',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',3);
INSERT INTO `generi` VALUES (12,'Roman - fragment',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (13,'Roman - historisk - alternativhistorie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (14,'Roman - historisk - ukroni',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (15,'Roman - historisk - kappe og kårde eller wuxia',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (16,'Roman - historisk - peplum eller sword and sandal',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (17,'Roman - science fiction - teknologisk science fiction - Singularity Fiction',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (18,'Roman - science fiction - teknologisk science fiction - cyberpunk - postcyberpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (19,'Roman - science fiction - teknologisk science fiction - cyberpunk - biopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (20,'Roman - science fiction - teknologisk science fiction - cyberpunk - nanopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (21,'Roman - science fiction - teknologisk science fiction - cyberpunk - dieselpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (22,'Roman - science fiction - teknologisk science fiction - cyberpunk - decopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (23,'Roman - science fiction - teknologisk science fiction - cyberpunk - swordpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (24,'Roman - science fiction - teknologisk science fiction - cyberpunk - sandalpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (25,'Roman - science fiction - teknologisk science fiction - cyberpunk - rokokopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (26,'Roman - science fiction - teknologisk science fiction - cyberpunk - nowpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (27,'Roman - science fiction - teknologisk science fiction - cyberpunk - steelpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (28,'Roman - science fiction - teknologisk science fiction - cyberpunk - raypunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (29,'Roman - science fiction - teknologisk science fiction - cyberpunk - dreampunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (30,'Roman - science fiction - teknologisk science fiction - cyberpunk - elfpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (31,'Roman - science fiction - teknologisk science fiction - cyberpunk - ecopunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (32,'Roman - science fiction - teknologisk science fiction - cyberpunk - clockpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (33,'Roman - science fiction - teknologisk science fiction - cyberpunk - atompunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (34,'Roman - science fiction - teknologisk science fiction - cyberpunk - mythpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (35,'Roman - science fiction - teknologisk science fiction - cyberpunk - stonepunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (36,'Roman - science fiction - teknologisk science fiction - cyberpunk - steampunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (37,'Roman - science fiction - teknologisk science fiction - cyberpunk - solarpunk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (38,'Roman - science fiction - teknologisk science fiction - space opera - militær space opera',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (39,'Roman - science fiction - teknologisk science fiction - space opera - space western',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (40,'Roman - science fiction - teknologisk science fiction - space opera - xenofiktion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (41,'Roman - science fiction - teknologisk science fiction - apokalyptisk og postapokalyptisk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (42,'Roman - science fiction - teknologisk science fiction - planetary romance og sword and planet',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (43,'Roman - science fiction - teknologisk science fiction - tidsrejser',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (44,'Roman - science fiction - teknologisk science fiction - new wave',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (45,'Roman - science fiction - teknologisk science fiction - edisonade',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (46,'Roman - science fiction - politisk science fiction - utopi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (47,'Roman - science fiction - politisk science fiction - dystopi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (48,'Roman - fantasy - high fantasy eller episk fantasy - sword and sorcery',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (49,'Roman - fantasy - high fantasy eller episk fantasy - dark fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (50,'Roman - fantasy - low fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (51,'Roman - fantasy - magisk realisme',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (52,'Roman - fantasy - nutidsfantasy - urban fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (53,'Roman - fantasy - nutidsfantasy - bangsiansk fantasy',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (54,'Roman - eventyrroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (55,'Roman - dannelsesroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (56,'Roman - føljetonroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (57,'Roman - ungdomsroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (58,'Roman - gyserroman - gotisk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (59,'Roman - actionroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (60,'Roman - spionroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (61,'Roman - thriller - mysterie-thriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (62,'Roman - thriller - psykologisk thriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (63,'Roman - thriller - spionthriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (64,'Roman - thriller - noir-thriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (65,'Roman - thriller - action-thriller - pulp - krimithriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (66,'Roman - thriller - teknothriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (67,'Roman - thriller - retsthriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (68,'Roman - thriller - politisk thriller - konspirationsthriller',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (69,'Roman - krimi - retskrimi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (70,'Roman - krimi - lægekrimi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (71,'Roman - krimi - mysterium i det lukkede rum',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (72,'Roman - noir - storbynoir',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (73,'Roman - hardboiled',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (74,'Roman - softboiled',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (75,'Roman - politiroman - police procedural',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (76,'Roman - kærlighedsroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (77,'Roman - erotisk roman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (78,'Roman - psykologisk roman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (79,'Roman - humoristisk roman - sort humor',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (80,'Roman - humoristisk roman - satire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (81,'Roman - humoristisk roman - parodi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (82,'Roman - socialroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (83,'Roman - brevroman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (84,'Novelle - samme undergenrer som romanen',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (85,'Eventyr',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (86,'Prosafabel',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (87,'Historieskrivning - monografi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (88,'Historieskrivning - annaler',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (89,'Historieskrivning - krønike',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (90,'Historieskrivning - verdenshistorie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (91,'Biografi - selvbiografi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (92,'Biografi - erindringslitteratur',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (93,'Dagbog',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',4);
INSERT INTO `generi` VALUES (94,'Dialog',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (95,'Afhandling',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (96,'Essay',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (97,'Pjece - smædeskrift',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (98,'Aforisme',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (99,'Apologi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (100,'Parabel',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (101,'Manifest',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (102,'Emblematik',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (103,'Prosaepistel - privat',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (104,'Prosaepistel - offentlig',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (105,'aretalogi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (106,'hagiografi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (107,'kerygmatisk biografi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (108,'filosofisk roman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (109,'undersøgende roman',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',5);
INSERT INTO `generi` VALUES (110,'Retorik - epideiktisk retorik',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT INTO `generi` VALUES (111,'Retorik - juridisk retorik',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT INTO `generi` VALUES (112,'Retorik - rådgivende retorik',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',6);
INSERT INTO `generi` VALUES (113,'Episk digt - historisk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (114,'Episk digt - mytologisk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (115,'Episk digt - kollektivt',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (116,'Episk digt - ridderepos',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (117,'Episk digt - kortere episk digt',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (118,'Epyllion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (119,'Heltekomisk digt - kortere heltekomisk digt',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',7);
INSERT INTO `generi` VALUES (120,'Didaktisk-allegorisk digt - kortere didaktisk-allegorisk digt',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (121,'Didaktisk digt - kortere didaktisk digt',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (122,'Visdomsdigt - kortere visdomsdigt',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (123,'Profeti',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (124,'versfabel',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (125,'filosofisk versepistel',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',8);
INSERT INTO `generi` VALUES (126,'monodisk lyrik - elegi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (127,'monodisk lyrik - jambe - kinaidion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (128,'monodisk lyrik - jambe - meliambe',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (129,'korlyrik - dithyrambe',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (130,'korlyrik - encomium',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (131,'korlyrik - epicedium',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (132,'korlyrik - epinikion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (133,'korlyrik - epithalamium',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (134,'korlyrik - hymenaios',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (135,'korlyrik - hymne',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (136,'korlyrik - hyporchema',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (137,'korlyrik - nomos',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (138,'korlyrik - partheneion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (139,'korlyrik - pæan',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (140,'korlyrik - prosodion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (141,'korlyrik - skolion',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (142,'korlyrik - threnos',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (143,'Bøn',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (144,'Lauda',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (145,'Bukolisk poesi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (146,'Satire',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (147,'Sonet',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (148,'Kanzone - petrarkisk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (149,'Kanzone - fri',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (150,'Capitolo (digtform)',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (151,'Carme (digt)',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (152,'Ode',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (153,'Madrigal',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (154,'Ballade',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (155,'Kort lyrisk digt',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (156,'Cento',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (157,'Frie vers',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (158,'Kalligram',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (159,'Lyrisk epistel',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',9);
INSERT INTO `generi` VALUES (160,'Tragedie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (161,'Komedie',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (162,'Drama',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (163,'Melodrama',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (164,'Commedia dell''arte',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (165,'Farce',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (166,'Sketch',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (167,'Prosamime',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',10);
INSERT INTO `generi` VALUES (168,'Opera - opera seria',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (169,'Opera - opera buffa',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (170,'Opera - operette',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (171,'Opera - farce',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (172,'Opera - zarzuela',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (173,'Opera - intermezzi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (174,'Ballet',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (175,'Pantomime',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (176,'Lyrisk mime - mimiambe',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (177,'Lyrisk mime - hilarodi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (178,'Lyrisk mime - magodi',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (179,'Lyrisk mime - musikalsk',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (180,'Musikdrama',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `generi` VALUES (181,'Oratorium',NULL,'2025-10-20 16:20:00','2025-10-20 16:20:00',11);
INSERT INTO `home_content` (section_key, title, subtitle, content, button_text, button_link, is_active, display_order, created_at, updated_at) VALUES
('hero', 'Dit digitale bibliotek', 'Udforsk, reservér og administrer din bogsamling', NULL, 'Udforsk kataloget', '/katalog', 1, -2, NOW(), NOW()),
('features_title', 'Hvorfor vælge Pinakes', 'En moderne, intuitiv oplevelse af biblioteksadministration, altid lige ved hånden', NULL, NULL, NULL, 1, 0, NOW(), NOW()),
('feature_1', 'Forenklet administration', 'Katalogiser dine bøger, håndter lån og afleveringer med en intuitiv og hurtig grænseflade', 'fas fa-tasks', NULL, NULL, 1, 1, NOW(), NOW()),
('feature_2', 'Komplet katalogisering', 'Importer data fra ISBN, organiser efter kategorier, generer etiketter og spor hvert fysisk eksemplar', 'fas fa-book', NULL, NULL, 1, 2, NOW(), NOW()),
('feature_3', 'Lånesystem', 'Håndter lån, forfaldsdatoer, fornyelser og automatiske e-mailnotifikationer til brugere og personale', 'fas fa-exchange-alt', NULL, NULL, 1, 3, NOW(), NOW()),
('feature_4', 'Open source og gratis', '100% gratis software uden licensomkostninger. Tilpas og bidrag til Pinakes-projektet', 'fas fa-code-branch', NULL, NULL, 1, 4, NOW(), NOW()),
('text_content', 'Πίνακες (Pinakes) – "Tavlerne"', NULL, '<p>Navnet <strong>Pinakes</strong> stammer fra det oldgræske <em>πίνακες</em> (pinakes), som betyder "tavler" eller "tabeller". Det hylder <strong>Kallimachos fra Kyrene</strong> (305-240 f.Kr.), som omkring 245 f.Kr. skabte det første systematiske bibliotekskatalog i historien for Biblioteket i Alexandria: <em>Πίνακες τῶν ἐν πάσῃ παιδείᾳ διαλαμψάντων καὶ ὧν συνέγραψαν</em> ("Tavler over dem, der har udmærket sig inden for ethvert vidensområde, og deres værker").</p><p>Dette monumentale værk, bestående af 120 ruller, organiserede systematisk over 120.000 papyrusruller i biblioteket. Selvom de originale <em>Pinakes</em> er gået tabt, har deres katalogiseringsmetode haft dybtgående indflydelse på moderne biblioteksvidenskab.</p><p>Dette projekt viderefører den årtusindgamle tradition på <strong>2.268 år</strong> ved at bringe de samme principper om organisering og tilgængelighed af viden ind i den digitale tidsalder.</p>', NULL, NULL, 1, 4, NOW(), NOW()),
('latest_books_title', 'Seneste tilføjelser', 'Opdag de seneste tilføjelser til kataloget', NULL, NULL, NULL, 1, 5, NOW(), NOW()),
('genre_carousel', 'Udforsk de vigtigste genrer', 'Udforsk vores tematiske rødder, og lad dig inspirere af de tilgængelige titler.', NULL, NULL, NULL, 1, 6, NOW(), NOW()),
('events', 'Kommende arrangementer', 'Deltag i vores næste møder', NULL, NULL, NULL, 1, 7, NOW(), NOW()),
('cta', 'Klar til at komme i gang?', 'Registrer dig nu, og begynd at udforske vores katalog', NULL, 'Registrer dig nu', '/registrer', 1, 8, NOW(), NOW());
SET FOREIGN_KEY_CHECKS=1;

-- Themes with Danish descriptions
INSERT INTO `themes` (`name`, `slug`, `version`, `author`, `description`, `active`, `settings`) VALUES
('Pinakes Classic', 'default', '1.0.0', 'Pinakes Team', 'Standardtema med Pinakes\' oprindelige magentafarver', 1, '{"colors": {"primary": "#d70161", "secondary": "#111827", "button": "#d70262", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Minimal', 'minimal-bw', '1.0.0', 'Pinakes Team', 'Minimalistisk design med sort, grå og hvid for et rent og elegant udtryk', 0, '{"colors": {"primary": "#404040", "secondary": "#000000", "button": "#808080", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Ocean Blue', 'ocean-blue', '1.0.0', 'Pinakes Team', 'Moderne og professionelle havblå nuancer til en frisk brugerflade', 0, '{"colors": {"primary": "#0284c7", "secondary": "#0c4a6e", "button": "#0ea5e9", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Forest Green', 'forest-green', '1.0.0', 'Pinakes Team', 'Naturlig smaragdgrøn, der fremkalder naturens ro', 0, '{"colors": {"primary": "#059669", "secondary": "#064e3b", "button": "#10b981", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Sunset Orange', 'sunset-orange', '1.0.0', 'Pinakes Team', 'Varm og indbydende orange inspireret af middelhavssolnedgange', 0, '{"colors": {"primary": "#ea580c", "secondary": "#7c2d12", "button": "#f97316", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Burgundy', 'burgundy-red', '1.0.0', 'Pinakes Team', 'Elegant og raffineret bordeauxrød til et sofistikeret udtryk', 0, '{"colors": {"primary": "#be123c", "secondary": "#881337", "button": "#e11d48", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Teal Professional', 'teal-professional', '1.0.0', 'Pinakes Team', 'Professionel blågrøn, perfekt til erhvervsmiljøer', 0, '{"colors": {"primary": "#0d9488", "secondary": "#134e4a", "button": "#14b8a6", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Slate Gray', 'slate-gray', '1.0.0', 'Pinakes Team', 'Moderne skifergrå til et neutralt og nutidigt design', 0, '{"colors": {"primary": "#475569", "secondary": "#1e293b", "button": "#64748b", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Coral Warm', 'coral-warm', '1.0.0', 'Pinakes Team', 'Varme og indbydende koralnuancer til en behagelig atmosfære', 0, '{"colors": {"primary": "#f43f5e", "secondary": "#9f1239", "button": "#fb7185", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}'),
('Navy Classic', 'navy-classic', '1.0.0', 'Pinakes Team', 'Klassisk og tidløs marineblå til et institutionelt udtryk', 0, '{"colors": {"primary": "#1e40af", "secondary": "#1e3a8a", "button": "#3b82f6", "button_text": "#ffffff"}, "typography": {"font_family": "system-ui, sans-serif", "font_size_base": "16px"}, "logo": {"url": "", "width": "auto", "height": "50px"}, "advanced": {"custom_css": "", "custom_js": ""}}');

-- CMS pages in Danish
INSERT INTO `cms_pages` VALUES (1,'chi-siamo','da_DK','Om os','<h2>Velkommen til Pinakes</h2>\n<p>Pinakes er et moderne, intuitivt og helt gratis biblioteksadministrationssystem. Bygget til at forenkle bogkatalogisering, håndtering af lån og administration af biblioteker af enhver størrelse.</p>\n\n<h3>🎯 Vores mission</h3>\n<p>At gøre biblioteksadministration tilgængelig for alle, uden licensomkostninger eller begrænsninger. Pinakes er 100% open source, frit og gratis for alle.</p>\n\n<h3>✨ Vigtigste funktioner</h3>\n<ul>\n    <li><strong>Smart katalogisering:</strong> Importer automatisk data fra ISBN, organiser efter kategorier, forfattere og brugerdefinerede klassifikationer</li>\n    <li><strong>Lånehåndtering:</strong> Komplet system til håndtering af lån, forfaldsdatoer, fornyelser og afleveringer</li>\n    <li><strong>Automatiske notifikationer:</strong> Påmindelser via e-mail om lånefrister og kommunikation med brugerne</li>\n    <li><strong>Moderne grænseflade:</strong> Responsivt design optimeret til computer, tablet og smartphone</li>\n    <li><strong>100% open source:</strong> Fri kode, tilpasningsbar og uden skjulte omkostninger</li>\n</ul>\n\n<h3>🚀 Hvorfor vælge Pinakes?</h3>\n<p>Pinakes opstod ud fra behovet for at tilbyde et professionelt, pålideligt og gratis værktøj til administration af skolebiblioteker, foreninger og private samlinger. Du behøver ikke være it-ekspert: den intuitive grænseflade gør det muligt for alle at komme i gang med det samme.</p>\n\n<h3>📖 Kom i gang i dag</h3>\n<p>Tilpas denne side med oplysninger om dit bibliotek, dit team og dine services. Gå til admin-panelet (CMS &gt; Sider) for at redigere dette indhold og gøre det unikt.</p>\n\n<p><em>Dette er eksempelindhold. Tilpas det for at fortælle historien om dit bibliotek!</em></p>',NULL,NULL,1,'2025-10-01 10:35:27','2025-10-01 10:35:27');
INSERT INTO `cms_pages` VALUES (2,'privacy-policy','da_DK','Privatlivspolitik','<h2>Privatlivspolitik</h2>\n<p>Dette er en pladsholderside for privatlivspolitikken. Tilpas dette indhold i henhold til gældende lovgivning (GDPR) og de specifikke behov i dit bibliotek.</p>\n\n<h3>1. Dataansvarlig</h3>\n<p>[Indsæt oplysninger om den dataansvarlige her: navn, adresse, e-mail, telefon]</p>\n\n<h3>2. Indsamlede data</h3>\n<p>Personoplysninger indsamlet gennem dette system omfatter:</p>\n<ul>\n    <li>Personoplysninger (navn, efternavn, fødselsdato)</li>\n    <li>Kontaktoplysninger (e-mail, telefon, adresse)</li>\n    <li>Data vedrørende foretagne lån</li>\n</ul>\n\n<h3>3. Formål med behandlingen</h3>\n<p>Data behandles udelukkende til:</p>\n<ul>\n    <li>Administration af brugerregister</li>\n    <li>Administration af biblioteksudlån</li>\n    <li>Afsendelse af lånerelateret kommunikation (forfaldsdatoer, fornyelser)</li>\n</ul>\n\n<h3>4. Den registreredes rettigheder</h3>\n<p>Brugere har ret til at få adgang til deres data samt anmode om berigtigelse, sletning eller begrænsning af behandlingen, som fastsat i Forordning (EU) 2016/679 (GDPR).</p>\n\n<p><strong>VIGTIGT:</strong> Dette er en eksempelskabelon. Kontakt en juridisk rådgiver for at udarbejde en privatlivspolitik, der overholder gældende lovgivning.</p>\n\n<p><em>Gå til admin-panelet (CMS &gt; Sider) for at tilpasse denne side.</em></p>',NULL,NULL,1,'2025-10-01 10:35:27','2025-10-01 10:35:27');

-- Email Templates - Italian only
INSERT INTO `email_templates` VALUES (1,'admin_new_registration','da_DK','👤 Ny registreringsanmodning','\n            <h2>Ny registreringsanmodning</h2>\n            <p>En ny bruger har anmodet om adgang til Pinakes:</p>\n            <p><strong>Brugeroplysninger:</strong></p>\n            <ul>\n                <li>Navn: {{nome}} {{cognome}}</li>\n                <li>Email: {{email}}</li>\n                <li>Medlemskort: {{codice_tessera}}</li>\n                <li>Anmodningsdato: {{data_registrazione}}</li>\n            </ul>\n            <p><a href="{{admin_users_url}}" style="background-color: #3b82f6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Administrer Brugere</a></p>\n        ','Email inviata agli admin quando un nuovo utente si registra.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (2,'admin_new_review','da_DK','⭐ Ny anmeldelse afventer godkendelse','<h2>Ny anmeldelse afventer godkendelse</h2>\n<p>Der er modtaget en ny anmeldelse af bogen:</p>\n<p><strong>Bog:</strong> {{libro_titolo}}</p>\n<div style="background-color: #fff7ed; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #f59e0b;">\n    <p><strong>Bedømmelse:</strong> {{stelle}} stjerner ⭐</p>\n    <p><strong>Bruger:</strong> {{utente_nome}} ({{utente_email}})</p>\n    <p><strong>Anmeldelsesdato:</strong> {{data_recensione}}</p>\n    <p><strong>Titel:</strong> {{titolo_recensione}}</p>\n    <p><strong>Beskrivelse:</strong></p>\n    <p style="white-space: pre-line;">{{descrizione_recensione}}</p>\n</div>\n<p style="text-align: center;">\n    <a href="{{link_approvazione}}" style="background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;">Administrer Anmeldelse</a>\n</p>\n<p><em>For at godkende eller afvise denne anmeldelse skal du logge ind i administrationspanelet.</em></p>','Inviata agli amministratori quando viene ricevuta una nuova recensione da approvare.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (3,'loan_approved','da_DK','✅ Din udlånsanmodning er blevet godkendt!','<h2>Din udlånsanmodning er blevet godkendt!</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Vi er glade for at kunne fortælle dig, at din udlånsanmodning er blevet <strong>godkendt</strong>!</p>\n<p><strong>Lånedetaljer:</strong></p>\n<ul>\n    <li>Bog: {{libro_titolo}}</li>\n    <li>Startdato for lån: {{data_inizio}}</li>\n    <li>Udløbsdato: {{data_fine}}</li>\n    <li>Varighed: {{giorni_prestito}} dage</li>\n</ul>\n<div style="background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;">\n    <p><strong>📦 Afhentning af bogen</strong></p>\n    <p>{{pickup_instructions}}</p>\n</div>\n<p><strong>Vigtigt:</strong> Husk at aflevere bogen inden udløbsdatoen. Du vil modtage en påmindelse et par dage før udløbet.</p>\n<p>God fornøjelse med læsningen!</p>','Inviata all\'utente quando un amministratore approva una richiesta di prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (4,'loan_rejected','da_DK','❌ Din udlånsanmodning er ikke blevet godkendt','<h2>Din udlånsanmodning er ikke blevet godkendt</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Vi må desværre meddele dig, at din udlånsanmodning for bogen <strong>"{{libro_titolo}}"</strong> ikke er blevet godkendt.</p>\n<div style="background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;">\n    <p><strong>Årsag:</strong></p>\n    <p>{{motivo_rifiuto}}</p>\n</div>\n<p>Hvis du har spørgsmål eller ønsker yderligere oplysninger, er du velkommen til at kontakte os.</p>\n<p>Med venlig hilsen,<br>Biblioteksteamet</p>','Inviata all\'utente quando un amministratore rifiuta una richiesta di prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (5,'loan_expiring_warning','da_DK','⚠️ Dit lån udløber snart','\n            <h2>Påmindelse om udløb af lån</h2>\n            <p>Hej {{utente_nome}},</p>\n            <p>Vi minder dig om, at dit lån snart udløber:</p>\n            <p><strong>Lånedetaljer:</strong></p>\n            <ul>\n                <li>Bog: {{libro_titolo}}</li>\n                <li>Udløbsdato: {{data_scadenza}}</li>\n                <li>Dage tilbage: {{giorni_rimasti}}</li>\n            </ul>\n            <div style="background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;">\n                <p><strong>⏰ Handling påkrævet</strong></p>\n                <p>For at undgå gebyrer skal du aflevere bogen inden udløbsdatoen eller kontakte biblioteket for en eventuel fornyelse.</p>\n            </div>\n            <p>Tak for samarbejdet!</p>\n        ','Email inviata all\'utente 3 giorni prima della scadenza del prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (6,'loan_overdue_admin','da_DK','Lån #{{prestito_id}} er forsinket','<h2>Forsinket lån</h2>\n<p>Lånet <strong>#{{prestito_id}}</strong> er nu i status <strong>forsinket</strong>.</p>\n<ul>\n  <li><strong>Bog:</strong> {{libro_titolo}}</li>\n  <li><strong>Bruger:</strong> {{utente_nome}} ({{utente_email}})</li>\n  <li><strong>Lånedato:</strong> {{data_prestito}}</li>\n  <li><strong>Udløbsdato:</strong> {{data_scadenza}}</li>\n</ul>\n<p>Grib ind for at kontakte brugeren og rykke for aflevering.</p>','Avvisa gli amministratori quando un prestito entra in ritardo.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (7,'loan_overdue_notification','da_DK','🚨 Lån udløbet - Handling påkrævet','\n            <h2>Lån udløbet</h2>\n            <p>Hej {{utente_nome}},</p>\n            <p>Dit lån er udløbet og skal afleveres omgående:</p>\n            <p><strong>Lånedetaljer:</strong></p>\n            <ul>\n                <li>Bog: {{libro_titolo}}</li>\n                <li>Udløbsdato: {{data_scadenza}}</li>\n                <li>Dage forsinket: {{giorni_ritardo}}</li>\n            </ul>\n            <div style="background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;">\n                <p><strong>🚨 Akut handling påkrævet</strong></p>\n                <p>Bogen skal afleveres omgående. Forsinket aflevering kan medføre sanktioner og suspendering af tjenesten.</p>\n            </div>\n            <p>Kontakt biblioteket omgående for at løse situationen.</p>\n        ','Email inviata all\'utente quando il prestito è scaduto.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (8,'loan_request_notification','da_DK','📚 Ny udlånsanmodning','\n            <h2>Ny udlånsanmodning</h2>\n            <p>Der er modtaget en ny udlånsanmodning:</p>\n            <p><strong>Detaljer:</strong></p>\n            <ul>\n                <li>Bog: {{libro_titolo}}</li>\n                <li>Bruger: {{utente_nome}} ({{utente_email}})</li>\n                <li>Ønsket startdato: {{data_inizio}}</li>\n                <li>Ønsket slutdato: {{data_fine}}</li>\n                <li>Anmodningsdato: {{data_richiesta}}</li>\n            </ul>\n            <p><a href="{{approve_url}}" style="background-color: #10b981; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Administrer Anmodning</a></p>\n        ','Email inviata agli admin quando un utente richiede un prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (9,'user_account_approved','da_DK','Konto godkendt - Velkommen til biblioteket!','\n            <h2>Din konto er blevet godkendt!</h2>\n            <p>Hej {{nome}} {{cognome}},</p>\n            <p>Vi er glade for at kunne fortælle dig, at din konto er blevet godkendt af en administrator.</p>\n            <p>Du kan nu logge ind på systemet og begynde at booke bøger!</p>\n            <p><strong>Detaljer om din konto:</strong></p>\n            <ul>\n                <li>Email: {{email}}</li>\n                <li>Medlemskort: {{codice_tessera}}</li>\n            </ul>\n            <p><a href="{{login_url}}" style="background-color: #3b82f6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Log ind nu</a></p>\n            <p>Velkommen til vores digitale bibliotek!</p>\n        ','Email inviata quando un admin approva direttamente l\'account senza richiedere verifica email.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (10,'user_activation_with_verification','da_DK','Aktivér din konto - Bekræft email','\n            <h2>Din konto er blevet godkendt!</h2>\n            <p>Hej {{nome}} {{cognome}},</p>\n            <p>Vi er glade for at kunne fortælle dig, at din konto er blevet godkendt af en administrator.</p>\n            <p>📧 <strong>Bekræft din email</strong></p>\n            <p>For at fuldføre aktiveringen skal du klikke på knappen nedenfor for at bekræfte din emailadresse:</p>\n            <p style="text-align: center; margin: 30px 0;">\n                <a href="{{verification_url}}" style="background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block;">✅ Bekræft Email</a>\n            </p>\n            <p><strong>Detaljer om din konto:</strong></p>\n            <ul>\n                <li>Email: {{email}}</li>\n                <li>Medlemskort: {{codice_tessera}}</li>\n            </ul>\n            <div style="background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;">\n                <p><strong>⏰ Vigtigt</strong></p>\n                <p>Bekræftelseslinket er gyldigt i 7 dage. Efter bekræftelsen kan du logge ind på systemet og booke bøger.</p>\n            </div>\n            <p>Hvis du ikke har anmodet om denne registrering, kan du se bort fra denne email.</p>\n        ','Email inviata quando un admin approva l\'account richiedendo la verifica email.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (11,'user_registration_pending','da_DK','Registrering modtaget - Afventer godkendelse','\n            <h2>Velkommen {{nome}} {{cognome}}!</h2>\n            <p>Din registreringsanmodning er blevet modtaget.</p>\n            <p><strong>Kontodetaljer:</strong></p>\n            <ul>\n                <li>Email: {{email}}</li>\n                <li>Medlemskort: {{codice_tessera}}</li>\n                <li>Registreringsdato: {{data_registrazione}}</li>\n            </ul>\n            {{sezione_verifica}}\n            <div style="background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;">\n                <p><strong>⏳ Konto afventer godkendelse</strong></p>\n                <p>Din konto afventer godkendelse af en administrator.\n                Du vil modtage en bekræftelsesmail, når kontoen er blevet aktiveret.</p>\n            </div>\n            <p>Tak, fordi du valgte Pinakes!</p>\n        ','Email inviata all\'utente dopo la registrazione, quando l\'account è in attesa di approvazione.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (12,'wishlist_book_available','da_DK','📖 Bog fra din ønskeliste er nu tilgængelig!','\n            <h2>Gode nyheder!</h2>\n            <p>Hej {{utente_nome}},</p>\n            <p>Bogen, du tilføjede til din ønskeliste, er nu tilgængelig til udlån:</p>\n            <div style="background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;">\n                <h3 style="color: #1e40af; margin: 0 0 10px 0;">{{libro_titolo}}</h3>\n                <p style="margin: 5px 0;"><strong>Forfatter:</strong> {{libro_autore}}</p>\n                <p style="margin: 5px 0;"><strong>ISBN:</strong> {{libro_isbn}}</p>\n                <p style="margin: 5px 0;"><strong>Tilgængelig fra:</strong> {{data_disponibilita}}</p>\n            </div>\n            <div style="background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0;">\n                <p><strong>✨ Reservér med det samme!</strong></p>\n                <p>Bogen er nu tilgængelig til reservation. Skynd dig, før en anden reserverer den!</p>\n            </div>\n            <p style="text-align: center;">\n                <a href="{{book_url}}" style="background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;">📚 Reservér Nu</a>\n                <a href="{{wishlist_url}}" style="background-color: #6b7280; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;">❤️ Administrér Ønskeliste</a>\n            </p>\n            <p><em>Bogen bliver på din ønskeliste; du vil ikke modtage flere notifikationer om denne titel.</em></p>\n        ','Email inviata quando un libro della wishlist diventa disponibile.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (13,'reservation_book_available','da_DK','📚 Reserveret bog klar til afhentning!','<h2>Din bog er klar til afhentning!</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Vi er glade for at kunne informere dig om, at bogen, du havde reserveret, nu er tilgængelig og klar til afhentning:</p>\n<div style="background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;">\n    <h3 style="color: #1e40af; margin: 0 0 10px 0;">{{libro_titolo}}</h3>\n    <p style="margin: 5px 0;"><strong>Forfatter:</strong> {{libro_autore}}</p>\n    <p style="margin: 5px 0;"><strong>ISBN:</strong> {{libro_isbn}}</p>\n    <p style="margin: 5px 0;"><strong>Lånperiode:</strong> {{data_inizio}} - {{data_fine}}</p>\n</div>\n<div style="background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;">\n    <p><strong>📦 Næste skridt</strong></p>\n    <p>Kom forbi biblioteket for at hente bogen. Husk at medbringe et gyldigt legitimationsdokument.</p>\n</div>\n<p style="text-align: center;">\n    <a href="{{book_url}}" style="background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;">📖 Se Bog</a>\n    <a href="{{profile_url}}" style="background-color: #6b7280; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; margin: 10px;">👤 Mine Lån</a>\n</p>\n<p><em>Reservationen er blevet konverteret til et lån, der afventer bekræftelse af afhentning.</em></p>','Email inviata quando un libro prenotato diventa disponibile e viene convertito in prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (14,'user_password_setup','da_DK','🔐 Opret din adgangskode','<h2>Opret din adgangskode</h2>\n<p>Hej {{nome}} {{cognome}},</p>\n<p>Din konto på <strong>{{app_name}}</strong> er blevet oprettet. For at begynde at bruge systemet skal du oprette din adgangskode.</p>\n<div style="background-color: #f0f9ff; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #3b82f6;">\n    <p><strong>🔑 Konfigurér din konto</strong></p>\n    <p>Klik på knappen nedenfor for at oprette din adgangskode:</p>\n</div>\n<p style="text-align: center; margin: 30px 0;">\n    <a href="{{reset_url}}" style="background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block;">🔐 Opret Adgangskode</a>\n</p>\n<div style="background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;">\n    <p><strong>⏰ Vigtigt</strong></p>\n    <p>Linket er gyldigt i 24 timer. Hvis det udløber, bedes du kontakte en administrator for at få et nyt.</p>\n</div>\n<p>Hvis du ikke har anmodet om denne e-mail, kan du se bort fra den.</p>','Email inviata ai nuovi utenti per impostare la password del loro account.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (15,'admin_invitation','da_DK','🎉 Invitation som Administrator','<h2>Velkommen til teamet!</h2>\n<p>Hej {{nome}} {{cognome}},</p>\n<p>Du er blevet inviteret som administrator på <strong>{{app_name}}</strong>.</p>\n<div style="background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;">\n    <h3 style="color: #1e40af; margin: 0 0 10px 0;">Dine adgangsrettigheder</h3>\n    <p>Som administrator vil du have adgang til:</p>\n    <ul>\n        <li>Administration af bogkatalog</li>\n        <li>Administration af brugere og lån</li>\n        <li>Systemindstillinger</li>\n        <li>Rapporter og statistik</li>\n    </ul>\n</div>\n<p><strong>Sådan kommer du i gang:</strong></p>\n<ol>\n    <li>Opret din adgangskode ved at klikke på knappen nedenfor</li>\n    <li>Log ind på administrationspanelet</li>\n</ol>\n<p style="text-align: center; margin: 30px 0;">\n    <a href="{{reset_url}}" style="background-color: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block; margin: 10px;">🔐 Opret Adgangskode</a>\n    <a href="{{dashboard_url}}" style="background-color: #3b82f6; color: white; padding: 12px 30px; text-decoration: none; border-radius: 8px; font-size: 16px; display: inline-block; margin: 10px;">📊 Admin Dashboard</a>\n</p>\n<div style="background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0;">\n    <p><strong>⏰ Vigtigt</strong></p>\n    <p>Linket til oprettelse af adgangskode er gyldigt i 24 timer.</p>\n</div>\n<p>Velkommen til teamet!</p>','Email inviata quando un utente viene invitato come amministratore.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (16,'loan_pickup_ready','da_DK','📦 Bog klar til afhentning!','<h2>Bog klar til afhentning!</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Vi er glade for at kunne informere dig om, at din bog er klar til afhentning!</p>\n<div style="background-color: #f0f9ff; padding: 20px; border-radius: 10px; border-left: 4px solid #3b82f6; margin: 20px 0;">\n    <h3 style="color: #1e40af; margin: 0 0 10px 0;">{{libro_titolo}}</h3>\n    <p style="margin: 5px 0;"><strong>Lånperiode:</strong> {{data_inizio}} - {{data_fine}}</p>\n    <p style="margin: 5px 0;"><strong>Varighed:</strong> {{giorni_prestito}} dage</p>\n</div>\n<div style="background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #f59e0b;">\n    <p><strong>⏰ Afhentningsfrist: {{scadenza_ritiro}}</strong></p>\n    <p>Afhent bogen inden denne dato, ellers annulleres lånet automatisk.</p>\n</div>\n<div style="background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;">\n    <p><strong>📦 Sådan afhenter du</strong></p>\n    <p>{{pickup_instructions}}</p>\n</div>\n<p>God fornøjelse med læsningen!</p>','Inviata quando un prestito è stato approvato e il libro è pronto per il ritiro.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (17,'loan_pickup_expired','da_DK','⏰ Afhentningsfristen er udløbet','<h2>Afhentningsfristen er udløbet</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Desværre har du ikke afhentet bogen inden for den fastsatte frist.</p>\n<div style="background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;">\n    <p><strong>Bog:</strong> {{libro_titolo}}</p>\n    <p><strong>Afhentningsfrist:</strong> {{scadenza_ritiro}}</p>\n</div>\n<p>Lånet er automatisk blevet annulleret, og bogen er blevet gjort tilgængelig for andre brugere.</p>\n<p>Hvis du stadig ønsker denne bog, opfordrer vi dig til at indsende en ny låneanmodning.</p>\n<p>Med venlig hilsen,<br>Bibliotekets team</p>','Inviata quando il tempo per ritirare un libro è scaduto e il prestito è stato annullato.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (18,'loan_pickup_cancelled','da_DK','❌ Afhentning annulleret','<h2>Afhentning annulleret</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Vi informerer dig om, at afhentningen af følgende bog er blevet annulleret:</p>\n<div style="background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;">\n    <p><strong>Bog:</strong> {{libro_titolo}}</p>\n    <p><strong>Årsag:</strong> {{motivo}}</p>\n</div>\n<p>Bogen er blevet gjort tilgængelig for andre brugere. Hvis du stadig ønsker denne bog, opfordrer vi dig til at indsende en ny låneanmodning.</p>\n<p>Med venlig hilsen,<br>Bibliotekets team</p>','Inviata quando un ritiro viene annullato dall''amministratore.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (19,'loan_returned','da_DK','✅ Aflevering bekræftet','<h2>Aflevering bekræftet</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Vi bekræfter afleveringen af følgende bog. Tak!</p>\n<div style="background-color: #ecfdf5; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #10b981;">\n    <p><strong>Bog:</strong> {{libro_titolo}}</p>\n    <p><strong>Afleveringsdato:</strong> {{data_restituzione}}</p>\n</div>\n<p>Vi håber, du nød læsningen. Vi ses snart på biblioteket!</p>\n<p>Med venlig hilsen,<br>Bibliotekets team</p>','Inviata all\'utente quando un prestito viene registrato come restituito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (20,'reservation_expired','da_DK','⌛ Reservationen er udløbet','<h2>Reservationen er udløbet</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Din reservation af følgende bog er udløbet og er blevet lukket automatisk:</p>\n<div style="background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;">\n    <p><strong>Bog:</strong> {{libro_titolo}}</p>\n    <p><strong>Udløbet den:</strong> {{data_scadenza}}</p>\n</div>\n<p>Hvis du stadig er interesseret, kan du foretage en ny reservation når som helst.</p>\n<p>Med venlig hilsen,<br>Bibliotekets team</p>','Inviata all\'utente quando una prenotazione scade automaticamente senza essere stata convertita in prestito.',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (21,'copy_unavailable_user','da_DK','ℹ️ Opdatering om din reservation','<h2>Opdatering om din reservation</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Vi informerer dig om, at det eksemplar, der var reserveret til din reservation af følgende bog, ikke længere er tilgængeligt:</p>\n<div style="background-color: #fffbeb; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #f59e0b;">\n    <p><strong>Bog:</strong> {{libro_titolo}}</p>\n    <p><strong>Årsag:</strong> {{motivo}}</p>\n</div>\n<p>Vi forsøger at tildele dig et andet eksemplar hurtigst muligt. Hvis der ikke bliver flere eksemplarer tilgængelige, forbliver din reservation i køen, og vi giver dig besked, så snart bogen igen er tilgængelig.</p>\n<p>Vi beklager ulejligheden.</p>\n<p>Med venlig hilsen,<br>Bibliotekets team</p>','Inviata all\'utente quando la copia riservata per la sua prenotazione diventa indisponibile (persa o danneggiata).',1,NULL,NULL);
INSERT INTO `email_templates` VALUES (22,'reservation_cancelled','da_DK','❌ Reservation annulleret','<h2>Reservation annulleret</h2>\n<p>Hej {{utente_nome}},</p>\n<p>Vi informerer dig om, at din reservation af følgende bog er blevet annulleret:</p>\n<div style="background-color: #fef2f2; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ef4444;">\n    <p><strong>Bog:</strong> {{libro_titolo}}</p>\n    <p><strong>Årsag:</strong> {{motivo}}</p>\n</div>\n<p>Hvis du stadig ønsker denne bog, kan du foretage en ny reservation når som helst.</p>\n<p>Med venlig hilsen,<br>Bibliotekets team</p>','Inviata all\'utente quando una prenotazione viene annullata dall\'amministrazione.',1,NULL,NULL);

-- ============================================================================
-- System Settings - Complete default configuration
-- These replace the old storage/settings.json file
-- ============================================================================

INSERT INTO `system_settings` (`category`, `setting_key`, `setting_value`, `description`, `updated_at`) VALUES
-- App settings
('app', 'name', 'Pinakes', 'Applikationsnavn', NOW()),
('app', 'logo_path', '', 'Sti til applikationens logo', NOW()),
('app', 'footer_description', 'Dit Pinakes-system til at katalogisere, administrere og dele din bogsamling.', 'Sidefodsbeskrivelse', NOW()),
('app', 'locale', 'da_DK', 'Default application locale', NOW()),
('app', 'social_facebook', '', 'Facebook-profil-URL', NOW()),
('app', 'social_twitter', '', 'Twitter-profil-URL', NOW()),
('app', 'social_instagram', '', 'Instagram-profil-URL', NOW()),
('app', 'social_linkedin', '', 'LinkedIn-profil-URL', NOW()),
('app', 'social_bluesky', '', 'Bluesky-profil-URL', NOW()),
('app', 'social_telegram', '', 'Telegram-kanal/gruppe-URL', NOW()),

-- Le impostazioni email sono configurate dall'utente nello step 6 dell'installer
-- Nessun valore predefinito qui per evitare di sovrascrivere le scelte dell'utente

-- Registration settings
('registration', 'require_admin_approval', '1', 'Kræv administratorgodkendelse for nye registreringer', NOW()),

-- Contacts page settings
('contacts', 'page_title', 'Kontakt os', 'Titel på kontaktsiden', NOW()),
('contacts', 'page_content', '<p>Kontakt os for yderligere oplysninger.</p>', 'Indhold på kontaktsiden', NOW()),
('contacts', 'contact_email', '', 'Kontakt-e-mailadresse', NOW()),
('contacts', 'contact_phone', '', 'Kontakttelefonnummer', NOW()),
('contacts', 'google_maps_embed', '', 'Indlejringskode til Google Maps', NOW()),
('contacts', 'privacy_text', 'Dine data er beskyttet i henhold til vores privatlivspolitik.', 'Privatlivsfriskrivningstekst', NOW()),
('contacts', 'recaptcha_site_key', '', 'reCAPTCHA-webstedsnøgle', NOW()),
('contacts', 'recaptcha_secret_key', '', 'reCAPTCHA-hemmelig nøgle', NOW()),
('contacts', 'notification_email', '', 'E-mail, hvor indsendelser fra kontaktformularen sendes', NOW()),

-- Privacy page settings
('privacy', 'page_title', 'Privatlivspolitik', 'Titel på privatlivspolitiksiden', NOW()),
('privacy', 'page_content', '<p>Dit privatliv er vigtigt for os.</p>', 'Indhold i privatlivspolitikken', NOW()),
('privacy', 'cookie_banner_enabled', '1', 'Aktiver cookie-samtykkebanner', NOW()),
('privacy', 'cookie_banner_language', 'da', 'Sprog for cookie-banner', NOW()),
('privacy', 'cookie_banner_country', 'DK', 'Land for cookie-banner', NOW()),
('privacy', 'cookie_statement_link', '', 'Link til cookieerklæring', NOW()),
('privacy', 'cookie_technologies_link', '', 'Link til side om cookieteknologier', NOW()),
('privacy', 'cookie_policy_content', '<p>Denne side forklarer, hvordan vi bruger cookies på vores websted.</p>', 'Indhold på cookiepolitiksiden', NOW()),

-- Cookie banner settings
('cookie_banner', 'banner_description', '<p>Vi bruger cookies til at forbedre din oplevelse. Ved at fortsætte med at besøge dette websted accepterer du vores brug af cookies.</p>', 'Beskrivelse af cookie-banner', NOW()),
('cookie_banner', 'accept_all_text', 'Accepter alle', 'Tekst til knappen "Accepter alle"', NOW()),
('cookie_banner', 'reject_non_essential_text', 'Afvis ikke-nødvendige', 'Tekst til knappen "Afvis ikke-nødvendige"', NOW()),
('cookie_banner', 'preferences_button_text', 'Præferencer', 'Tekst til knappen "Præferencer"', NOW()),
('cookie_banner', 'save_selected_text', 'Accepter valgte', 'Tekst til knappen "Gem valgte"', NOW()),
('cookie_banner', 'preferences_title', 'Tilpas dine cookiepræferencer', 'Titel på præferencevindue', NOW()),
('cookie_banner', 'preferences_description', '<p>Vi respekterer din ret til privatliv. Du kan vælge ikke at tillade visse typer cookies. Dine præferencer vil gælde for hele webstedet.</p>', 'Beskrivelse af præferencevindue', NOW()),
('cookie_banner', 'cookie_essential_name', 'Nødvendige cookies', 'Navn på nødvendige cookies', NOW()),
('cookie_banner', 'cookie_essential_description', 'Disse cookies er nødvendige for, at webstedet kan fungere, og kan ikke deaktiveres.', 'Beskrivelse af nødvendige cookies', NOW()),
('cookie_banner', 'show_analytics', '1', 'Vis mulighed for analytiske cookies', NOW()),
('cookie_banner', 'cookie_analytics_name', 'Analytiske cookies', 'Navn på analytiske cookies', NOW()),
('cookie_banner', 'cookie_analytics_description', 'Disse cookies hjælper os med at forstå, hvordan besøgende interagerer med webstedet.', 'Beskrivelse af analytiske cookies', NOW()),
('cookie_banner', 'show_marketing', '1', 'Vis mulighed for marketingcookies', NOW()),
('cookie_banner', 'cookie_marketing_name', 'Marketingcookies', 'Navn på marketingcookies', NOW()),
('cookie_banner', 'cookie_marketing_description', 'Disse cookies bruges til at levere personlige annoncer.', 'Beskrivelse af marketingcookies', NOW()),

-- Advanced settings
('advanced', 'custom_js_essential', '', 'Brugerdefineret JavaScript til nødvendige cookies', NOW()),
('advanced', 'custom_js_analytics', '', 'Brugerdefineret JavaScript til analytiske cookies', NOW()),
('advanced', 'custom_js_marketing', '', 'Brugerdefineret JavaScript til marketingcookies', NOW()),
('advanced', 'custom_header_css', '', 'Brugerdefineret CSS til header', NOW()),
('advanced', 'custom_header_js', '', 'Brugerdefineret JavaScript til header', NOW()),
('advanced', 'days_before_expiry_warning', '3', 'Antal dage før advarsel om udløb af kort', NOW()),
('advanced', 'sitemap_last_generated_at', '', 'Tidsstempel for seneste sitemap-generering', NOW()),
('advanced', 'sitemap_last_generated_total', '0', 'Samlet antal URL''er i det seneste genererede sitemap', NOW()),
('advanced', 'api_enabled', '0', 'Aktiver API-adgang', NOW()),

-- Label printing settings
('label', 'width', '25', 'Etiketbredde i mm', NOW()),
('label', 'height', '38', 'Etikethøjde i mm', NOW()),
('label', 'format_name', '25x38mm (Standard)', 'Navn på etiketformat', NOW()),

-- API settings
('api', 'enabled', '0', 'Aktiver API globalt', NOW()),

-- Social sharing settings
('sharing', 'enabled_providers', 'facebook,x,whatsapp,email', 'Aktiverede udbydere til social deling på bogens detaljeside', NOW())
ON DUPLICATE KEY UPDATE
    description = VALUES(description),
    updated_at = NOW();

-- Seed data for languages table
-- Issue #108: seed ALL shipped locales, not just the installer-chosen one,
-- so users whose `utenti.locale` differs from the install default
-- (e.g. a de_DE user on an it_IT install) can still have their locale
-- restored by RememberMeMiddleware → I18n::setLocale(), which gates on
-- `languages` table membership.
-- FIX F020: added ON DUPLICATE KEY UPDATE so re-running this seeder on an
-- existing DB (recovery / reinstall-test.sh path) doesn't fail with a
-- duplicate-key error on `languages.code`. Mirrors data_de_DE.sql:319.
-- FIX F023: total_keys/translated_keys/completion_percentage updated to real
-- JSON key counts (jq '[paths(scalars)] | length'): it_IT=493, en_US=4653,
-- de_DE=4653, fr_FR=4993. Previous values (2015/4009/4080) were stale and
-- inconsistent with migrate_0.7.5.sql (which used 4145). Fresh installs now
-- match the actual translation file contents.
INSERT INTO `languages` (`code`, `name`, `native_name`, `flag_emoji`, `is_default`, `is_active`, `translation_file`, `total_keys`, `translated_keys`, `completion_percentage`) VALUES
('it_IT', 'Italian', 'Italiano', '🇮🇹', 1, 1, NULL, 493, 493, 100.00),
('en_US', 'English', 'English', '🇬🇧', 0, 1, 'locale/en_US.json', 4653, 4653, 100.00),
('de_DE', 'German', 'Deutsch', '🇩🇪', 0, 1, 'locale/de_DE.json', 4653, 4653, 100.00),
('fr_FR', 'French', 'Français', '🇫🇷', 0, 1, 'locale/fr_FR.json', 4993, 4993, 100.00),
('da_DK', 'Danish', 'Dansk', '🇩🇰', 0, 1, 'locale/da_DK.json', 6604, 6604, 100.00)
ON DUPLICATE KEY UPDATE name = VALUES(name), native_name = VALUES(native_name), flag_emoji = VALUES(flag_emoji), translation_file = VALUES(translation_file), total_keys = VALUES(total_keys), translated_keys = VALUES(translated_keys), completion_percentage = VALUES(completion_percentage), is_active = VALUES(is_active), is_default = VALUES(is_default);


SET FOREIGN_KEY_CHECKS=1;
